---
- name: "Setup Docker"
  ansible.builtin.include_tasks:
    file: "install.yaml"

- name: "Copy Config files"
  become: true
  ansible.builtin.copy:
    src: "files/{{ item.name }}"
    dest: "{{ docker_base_path }}/{{ item.dir }}/{{ item.name }}"
    owner: "{{ item.owner | default(ansible_facts['user_id']) }}"
    group: "{{ item.group | default(ansible_facts['user_gid']) }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - name: "package.json"
      dir: "nodejs"
    - name: "mosquitto.conf"
      dir: "mqtt"
      owner: "1883"
  notify:
    - "Restart nodejs"

- name: "Copy data files"
  become: true
  ansible.builtin.copy:
    src: "files/{{ item.path }}"
    dest: "{{ docker_base_path }}/{{ item.dest }}"
    owner: "{{ item.owner | default(ansible_facts['user_id']) }}"
    group: "{{ item.group | default(ansible_facts['user_gid']) }}"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - path: "nodejs/app.js"
      dest: "nodejs/app.js"
    - path: "nodejs/public/"
      dest: "nodejs/public"
    - path: "nodejs/views/"
      dest: "nodejs/views"
  notify:
    - "Restart nodejs"

- name: "Create Network"
  community.docker.docker_network:
    driver: "bridge"
    ipam_config:
      - subnet: "{{ docker_project_network | default('192.168.55') }}.0/24"
    name: "soundcraftui16mqtt"

- name: "Create Container"
  community.docker.docker_compose_v2:
    project_name: "soundcraftui16mqtt"
    pull: "{{ docker_image_pull | default('missing') }}"
    state: "present"
    definition:
      networks:
        soundcraftui16mqtt:
          external: true
      services:
        nodejs:
          container_name: "nodejs"
          image: "node:25.0"
          restart: "unless-stopped"
          working_dir: "/home/node/app"
          volumes:
            - "{{ docker_base_path }}/nodejs:/home/node/app"
          ports:
            - "{{ docker_nodejs_port | default(3000) }}:3000"
          networks:
            soundcraftui16mqtt:
              aliases:
                - "nodejs"
          environment:
            NODE_ENV: "production"
          command: 'bash -c "
              npm install && npm start
            "'
        mqtt:
          container_name: "mqtt"
          image: "eclipse-mosquitto"
          restart: "unless-stopped"
          volumes:
            - "{{ docker_base_path }}/mqtt:/mosquitto/config"
          ports:
            - "{{ docker_mqtt_port | default(1883) }}:1883"
            - "{{ docker_mqtt_websocket_port | default(9001) }}:9001"
          user: "1883:1000"
          networks:
            soundcraftui16mqtt:
              aliases:
                - "mqtt"
...
